name: Create release

on:
  push:
    tags:
      - 'v[0-9]+.*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./barony-mod-manager

      - name: Build
        run: |
          sudo apt install libxkbcommon-dev
          cd barony-mod-manager
          cargo build --release
          strip target/release/barony-mod-manager
          mv target/release/barony-mod-manager target/release/barony-mod-manager_amd64

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: barony-mod-manager/target/release/barony-mod-manager_amd64
          body: For more information, read the [changelog](https://github.com/arcticlimer/barony-mod-manager/blob/master/CHANGELOG.md).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./barony-mod-manager

      - name: Build
        run: |
          cd barony-mod-manager
          cargo build --release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: barony-mod-manager/target/release/barony-mod-manager.exe
          body: For more information, read the [changelog](https://github.com/arcticlimer/barony-mod-manager/blob/master/CHANGELOG.md).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: ./barony-mod-manager

      - name: Build for mac
        run: |
          cd barony-mod-manager
          cargo build --release
          strip target/release/barony-mod-manager
          mv target/release/barony-mod-manager target/release/barony-mod-manager_darwin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: barony-mod-manager/target/release/barony-mod-manager_darwin
          body: For more information, read the [changelog](https://github.com/arcticlimer/barony-mod-manager/blob/master/CHANGELOG.md).
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
